// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAawKbc5Vk-3Y2eOTQx8w4ecYfDveKuWlg',
    appId: '1:498238732911:web:a8b8e45795fbdd8c666b9a',
    messagingSenderId: '498238732911',
    projectId: 'healthcare-d5d25',
    authDomain: 'healthcare-d5d25.firebaseapp.com',
    storageBucket: 'healthcare-d5d25.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC4OyJPZhW3ytU6extw-15GK-yHjQ6fq6s',
    appId: '1:498238732911:android:85355380238661a7666b9a',
    messagingSenderId: '498238732911',
    projectId: 'healthcare-d5d25',
    storageBucket: 'healthcare-d5d25.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCX898m53EL_H68UjQ8OCH-YP5NDBeyHxA',
    appId: '1:498238732911:ios:8137c6ef861cb07e666b9a',
    messagingSenderId: '498238732911',
    projectId: 'healthcare-d5d25',
    storageBucket: 'healthcare-d5d25.appspot.com',
    iosBundleId: 'com.example.healthCare',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCX898m53EL_H68UjQ8OCH-YP5NDBeyHxA',
    appId: '1:498238732911:ios:8137c6ef861cb07e666b9a',
    messagingSenderId: '498238732911',
    projectId: 'healthcare-d5d25',
    storageBucket: 'healthcare-d5d25.appspot.com',
    iosBundleId: 'com.example.healthCare',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAawKbc5Vk-3Y2eOTQx8w4ecYfDveKuWlg',
    appId: '1:498238732911:web:ed7ecfe86b8ab1b0666b9a',
    messagingSenderId: '498238732911',
    projectId: 'healthcare-d5d25',
    authDomain: 'healthcare-d5d25.firebaseapp.com',
    storageBucket: 'healthcare-d5d25.appspot.com',
  );
}
